In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("new.csv")
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (29,46,63) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.10,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
1,1,#29913,aishpawar9428@gmail.com,pending,NaN,fulfilled,2022-04-29 11:27:54 +0530,yes,INR,1399.00,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
2,2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.10,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
3,3,#29911,zuberali983@gmail.com,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,664.05,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
4,4,#29910,dr.ajaychauhan@yahoo.in,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,599.00,...,NaN,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN

In [3]:
df.columns

# Email
# Phone
# First Name
# Last Name
# Country
# Zip

Index(['Unnamed: 0', 'Name', 'Email', 'Financial Status', 'Paid at',
       'Fulfillment Status', 'Fulfilled at', 'Accepts Marketing', 'Currency',
       'Subtotal', 'Shipping', 'Taxes', 'Total', 'Discount Code',
       'Discount Amount', 'Shipping Method', 'Created at', 'Lineitem quantity',
       'Lineitem name', 'Lineitem price', 'Lineitem compare at price',
       'Lineitem sku', 'Lineitem requires shipping', 'Lineitem taxable',
       'Lineitem fulfillment status', 'Billing Name', 'Billing Street',
       'Billing Address1', 'Billing Address2', 'Billing Company',
       'Billing City', 'Billing Zip', 'Billing Province', 'Billing Country',
       'Billing Phone', 'Shipping Name', 'Shipping Street',
       'Shipping Address1', 'Shipping Address2', 'Shipping Company',
       'Shipping City', 'Shipping Zip', 'Shipping Province',
       'Shipping Country', 'Shipping Phone', 'Notes', 'Note Attributes',
       'Cancelled at', 'Payment Method', 'Payment Reference',
       'Refunded Amount', 'Vendor', 'Id', 'Tags', 'Risk Level', 'Source',
       'Lineitem discount', 'Tax 1 Name', 'Tax 1 Value', 'Tax 2 Name',
       'Tax 2 Value', 'Tax 3 Name', 'Tax 3 Value', 'Tax 4 Name', 'Tax 4 Value',
       'Tax 5 Name', 'Tax 5 Value', 'Phone', 'Receipt Number', 'Duties',
       'Billing Province Name', 'Shipping Province Name', 'Payment ID',
       'Payment Terms Name', 'Next Payment Due At'],
      dtype='object')

In [ ]:
ll = ['Name','Financial Status', 'Paid at','Fulfillment Status', 'Fulfilled at', 'Accepts Marketing', 'Currency','Subtotal', 'Shipping', 'Taxes', 'Total', 'Discount Code','Discount Amount', 'Shipping Method', 'Created at', 'Lineitem quantity','Lineitem name', 'Lineitem price', 'Lineitem compare at price','Lineitem sku', 'Lineitem requires shipping', 'Lineitem taxable','Lineitem fulfillment status', 'Billing Street','Billing Address1', 'Billing Address2', 'Billing Company','Billing City', 'Billing Province', 'Shipping Name', 'Shipping Street','Shipping Address1', 'Shipping Address2', 'Shipping Company','Shipping City', 'Shipping Zip', 'Shipping Province','Shipping Country', 'Shipping Phone', 'Notes', 'Note Attributes','Cancelled at', 'Payment Method', 'Payment Reference','Refunded Amount', 'Vendor', 'Id', 'Tags', 'Risk Level', 'Source','Lineitem discount', 'Tax 1 Name', 'Tax 1 Value', 'Tax 2 Name','Tax 2 Value', 'Tax 3 Name', 'Tax 3 Value', 'Tax 4 Name', 'Tax 4 Value','Tax 5 Name', 'Tax 5 Value', 'Phone', 'Receipt Number', 'Duties','Billing Province Name', 'Shipping Province Name', 'Payment ID','Payment Terms Name', 'Next Payment Due At']

In [ ]:
df.drop(['A'], axis = 1)