In [1]:
import pandas as pd 
import numpy as np

In [2]:
inp = input("Enter the file name : ")
csv1 = pd.read_csv(inp)
csv1.head()

Enter the file name : orders_export_1.csv

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (28,38,45,62) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
1,#29913,aishpawar9428@gmail.com,pending,NaN,fulfilled,2022-04-29 11:27:54 +0530,yes,INR,1399.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
3,#29911,zuberali983@gmail.com,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,664.05,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
4,#29910,dr.ajaychauhan@yahoo.in,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,599.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN

In [3]:
csv2 = pd.read_csv("orders_export_2.csv")
csv2.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (28,60) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,#14345,muneshchandra850@gmail.com,paid,2022-01-28 00:10:31 +0530,fulfilled,2022-01-23 16:22:20 +0530,yes,INR,689.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN
1,#14344,kamalkhatri8888@gmail.com,paid,2022-01-27 18:11:21 +0530,fulfilled,2022-01-23 16:22:20 +0530,yes,INR,998.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
2,#14344,kamalkhatri8888@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#14343,harshmaurya144@gmail.com,paid,2022-01-28 00:10:32 +0530,fulfilled,2022-01-23 16:22:20 +0530,yes,INR,509.86,0.0,...,NaN,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN
4,#14342,asmita.jalali@gmail.com,paid,2022-01-23 12:44:08 +0530,fulfilled,2022-01-23 16:24:01 +0530,yes,INR,824.40,0.0,...,NaN,NaN,NaN,NaN,NaN,Punjab,Punjab,NaN,NaN,NaN

In [4]:
concate_data = pd.concat([csv1, csv2])

In [5]:
concate_data.head()

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
1,#29913,aishpawar9428@gmail.com,pending,NaN,fulfilled,2022-04-29 11:27:54 +0530,yes,INR,1399.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
3,#29911,zuberali983@gmail.com,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,664.05,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
4,#29910,dr.ajaychauhan@yahoo.in,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,599.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN

In [6]:
concate_data.to_csv("milk.csv")

In [7]:
concate_data

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
1,#29913,aishpawar9428@gmail.com,pending,NaN,fulfilled,2022-04-29 11:27:54 +0530,yes,INR,1399.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.10,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
3,#29911,zuberali983@gmail.com,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,664.05,0.0,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
4,#29910,dr.ajaychauhan@yahoo.in,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,599.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9192,#6060,tiainla.tiainla@gmail.com,pending,NaN,fulfilled,2021-11-01 10:18:11 +0530,yes,INR,598.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Assam,Assam,NaN,NaN,NaN
9193,#6059,anmolkiran1512@gmail.com,pending,NaN,unfulfilled,NaN,yes,INR,404.00,40.0,...,NaN,NaN,NaN,NaN,NaN,Rajasthan,Rajasthan,NaN,NaN,NaN
9194,#6058,jabstome@gmail.com,paid,2021-11-01 02:00:23 +0530,fulfilled,2021-11-01 10:17:11 +0530,no,INR,644.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
9195,#6057,jabstome@gmail.com,pending,NaN,unfulfilled,NaN,yes,INR,694.00,0.0,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
9196,#6056,jasys.js@gmail.com,pending,NaN,fulfilled,2021-11-01 10:17:11 +0530,yes,INR,195.00,40.0,...,NaN,NaN,NaN,NaN,NaN,Meghalaya,Meghalaya,NaN,NaN,NaN

In [10]:
df = pd.read_csv("milk.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (29,46,63) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [11]:
df

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.10,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
1,1,#29913,aishpawar9428@gmail.com,pending,NaN,fulfilled,2022-04-29 11:27:54 +0530,yes,INR,1399.00,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
2,2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.10,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
3,3,#29911,zuberali983@gmail.com,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,664.05,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
4,4,#29910,dr.ajaychauhan@yahoo.in,pending,NaN,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,599.00,...,NaN,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26533,9192,#6060,tiainla.tiainla@gmail.com,pending,NaN,fulfilled,2021-11-01 10:18:11 +0530,yes,INR,598.00,...,NaN,NaN,NaN,NaN,NaN,Assam,Assam,NaN,NaN,NaN
26534,9193,#6059,anmolkiran1512@gmail.com,pending,NaN,unfulfilled,NaN,yes,INR,404.00,...,NaN,NaN,NaN,NaN,NaN,Rajasthan,Rajasthan,NaN,NaN,NaN
26535,9194,#6058,jabstome@gmail.com,paid,2021-11-01 02:00:23 +0530,fulfilled,2021-11-01 10:17:11 +0530,no,INR,644.00,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
26536,9195,#6057,jabstome@gmail.com,pending,NaN,unfulfilled,NaN,yes,INR,694.00,...,NaN,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN
26537,9196,#6056,jasys.js@gmail.com,pending,NaN,fulfilled,2021-11-01 10:17:11 +0530,yes,INR,195.00,...,NaN,NaN,NaN,NaN,NaN,Meghalaya,Meghalaya,NaN,NaN,NaN

In [12]:
filterdata = df[df['Financial Status'] == "paid"]

In [13]:
print(filterdata.shape)
filterdata.head()

(16036, 75)

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At
0,0,#29914,pankajgavri@gmail.com,paid,2022-04-28 23:57:34 +0530,fulfilled,2022-04-29 11:31:50 +0530,no,INR,719.1,...,NaN,NaN,NaN,NaN,NaN,Haryana,Haryana,NaN,NaN,NaN
2,2,#29912,zuberali983@gmail.com,paid,2022-04-28 23:25:11 +0530,fulfilled,2022-04-29 11:31:50 +0530,yes,INR,629.1,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
8,8,#29906,bhumikagupta1011@gmail.com,paid,2022-04-28 22:04:47 +0530,fulfilled,2022-04-29 11:31:53 +0530,yes,INR,719.1,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN
14,14,#29900,apstar0001@gmail.com,paid,2022-04-28 21:13:27 +0530,fulfilled,2022-04-29 11:27:09 +0530,no,INR,2601.1,...,NaN,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN
17,17,#29897,kshitij_raj09@yahoo.com,paid,2022-04-28 20:59:03 +0530,fulfilled,2022-04-29 11:31:53 +0530,yes,INR,674.1,...,NaN,NaN,NaN,NaN,NaN,Madhya Pradesh,Madhya Pradesh,NaN,NaN,NaN

In [14]:
df['birth_date'] = pd.to_datetime(filterdata['Fulfilled at'])
df
start_date = '29-03-2022' 
end_date = '29-04-2022'
mask = (df['birth_date'] > start_date) & (df['birth_date'] <= end_date)

In [15]:
df = df.loc[mask]
df

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,birth_date
19,19,#29895,'+919143934415@neu-herbs.myshopify.com,paid,2022-04-28 20:33:14 +0530,fulfilled,2022-04-28 22:24:06 +0530,no,INR,662.43,...,NaN,NaN,NaN,NaN,West Bengal,West Bengal,NaN,NaN,NaN,2022-04-28 22:24:06+05:30
55,55,#29865,'+918080784821@neu-herbs.myshopify.com,paid,2022-04-28 16:44:42 +0530,fulfilled,2022-04-28 18:26:40 +0530,no,INR,719.10,...,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:40+05:30
58,58,#29862,NaN,paid,2022-04-28 16:20:43 +0530,fulfilled,2022-04-28 18:26:42 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:42+05:30
59,59,#29861,NaN,paid,2022-04-28 16:20:42 +0530,fulfilled,2022-04-28 18:26:41 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:41+05:30
60,60,#29860,NaN,paid,2022-04-28 16:20:40 +0530,fulfilled,2022-04-28 18:26:41 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:41+05:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6506,6506,#24111,ravikantsingh789@gmail.com,paid,2022-03-28 16:29:00 +0530,fulfilled,2022-03-29 11:12:26 +0530,yes,INR,1273.30,...,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN,2022-03-29 11:12:26+05:30
6659,6659,#23970,chiragtnj@gmail.com,paid,2022-03-27 18:28:20 +0530,fulfilled,2022-03-29 10:03:11 +0530,yes,INR,1189.15,...,NaN,NaN,NaN,NaN,Rajasthan,Rajasthan,NaN,NaN,NaN,2022-03-29 10:03:11+05:30
6662,6662,#23967,rekha.dhumale@gmail.com,paid,2022-03-27 18:17:06 +0530,fulfilled,2022-03-29 10:02:53 +0530,no,INR,683.14,...,NaN,NaN,NaN,NaN,Gujarat,Gujarat,NaN,NaN,NaN,2022-03-29 10:02:53+05:30
6838,6838,#23815,manpreetkaur1592@yahoo.com,paid,2022-04-02 12:13:16 +0530,fulfilled,2022-03-29 10:02:41 +0530,yes,INR,607.50,...,NaN,NaN,NaN,NaN,Punjab,Punjab,NaN,NaN,NaN,2022-03-29 10:02:41+05:30
6839,6839,#23814,deeptidwivedihdi@gmail.com,paid,2022-03-26 18:13:13 +0530,fulfilled,2022-03-29 10:03:56 +0530,yes,INR,544.00,...,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN,2022-03-29 10:03:56+05:30

In [16]:
df.head()

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,birth_date
19,19,#29895,'+919143934415@neu-herbs.myshopify.com,paid,2022-04-28 20:33:14 +0530,fulfilled,2022-04-28 22:24:06 +0530,no,INR,662.43,...,NaN,NaN,NaN,NaN,West Bengal,West Bengal,NaN,NaN,NaN,2022-04-28 22:24:06+05:30
55,55,#29865,'+918080784821@neu-herbs.myshopify.com,paid,2022-04-28 16:44:42 +0530,fulfilled,2022-04-28 18:26:40 +0530,no,INR,719.10,...,NaN,NaN,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:40+05:30
58,58,#29862,NaN,paid,2022-04-28 16:20:43 +0530,fulfilled,2022-04-28 18:26:42 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:42+05:30
59,59,#29861,NaN,paid,2022-04-28 16:20:42 +0530,fulfilled,2022-04-28 18:26:41 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:41+05:30
60,60,#29860,NaN,paid,2022-04-28 16:20:40 +0530,fulfilled,2022-04-28 18:26:41 +0530,no,INR,567.00,...,NaN,9.198198e+11,NaN,NaN,Maharashtra,Maharashtra,NaN,NaN,NaN,2022-04-28 18:26:41+05:30

In [21]:

filterdata = df[df['Lineitem name'] == "neuherbs Milk Thistle (Detox Formula) - Pack of 1 (60 Capsules)"]

In [22]:
#  products are : 
#

In [23]:
filterdata

,Unnamed: 0,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,...,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,birth_date
713,713,#29271,naveenrana9271@gmail.com,paid,2022-04-29 12:13:06 +0530,fulfilled,2022-04-25 18:02:29 +0530,yes,INR,1398.0,...,NaN,NaN,NaN,NaN,Jammu and Kashmir,Jammu and Kashmir,NaN,NaN,NaN,2022-04-25 18:02:29+05:30
714,714,#29270,girish.patil0079@gmail.com,paid,2022-04-28 18:11:46 +0530,fulfilled,2022-04-25 18:02:55 +0530,yes,INR,699.0,...,NaN,NaN,NaN,NaN,Chandigarh,Chandigarh,NaN,NaN,NaN,2022-04-25 18:02:55+05:30
780,780,#29211,Mithunchaudhary559@gmail.com,paid,2022-04-25 12:17:59 +0530,fulfilled,2022-04-25 18:03:00 +0530,no,INR,629.1,...,NaN,NaN,NaN,NaN,NaN,Uttar Pradesh,NaN,NaN,NaN,2022-04-25 18:03:00+05:30
796,796,#29197,augustinthomas55@gmail.com,paid,2022-04-25 11:07:39 +0530,fulfilled,2022-04-25 18:03:05 +0530,no,INR,629.1,...,NaN,NaN,NaN,NaN,NaN,Karnataka,NaN,NaN,NaN,2022-04-25 18:03:05+05:30
817,817,#29181,bijaysaikia212345@gmail.com,paid,2022-04-25 09:41:57 +0530,fulfilled,2022-04-25 11:11:56 +0530,no,INR,629.1,...,NaN,NaN,NaN,NaN,NaN,Assam,NaN,NaN,NaN,2022-04-25 11:11:56+05:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6106,6106,#24464,virenderdavgen5@gmail.com,paid,2022-04-02 18:13:32 +0530,fulfilled,2022-03-31 10:51:17 +0530,yes,INR,699.0,...,NaN,NaN,NaN,NaN,Delhi,Delhi,NaN,NaN,NaN,2022-03-31 10:51:17+05:30
6154,6154,#24421,surinderlive@gmail.com,paid,2022-03-30 13:40:54 +0530,fulfilled,2022-03-30 15:36:16 +0530,no,INR,2772.8,...,NaN,NaN,NaN,NaN,NaN,Punjab,NaN,NaN,NaN,2022-03-30 15:36:16+05:30
6287,6287,#24298,debasisdutta008@gmail.com,paid,2022-04-02 12:14:28 +0530,fulfilled,2022-03-30 10:17:08 +0530,yes,INR,699.0,...,NaN,NaN,NaN,NaN,Odisha,Odisha,NaN,NaN,NaN,2022-03-30 10:17:08+05:30
6354,6354,#24243,viksingh9176@gmail.com,paid,2022-04-03 12:10:57 +0530,fulfilled,2022-03-29 16:59:28 +0530,yes,INR,699.0,...,NaN,NaN,NaN,NaN,Bihar,Bihar,NaN,NaN,NaN,2022-03-29 16:59:28+05:30
6360,6360,#24239,pandit.mani7@gmail.com,paid,2022-03-31 18:12:50 +0530,fulfilled,2022-03-29 16:59:29 +0530,yes,INR,699.0,...,NaN,NaN,NaN,NaN,Uttar Pradesh,Uttar Pradesh,NaN,NaN,NaN,2022-03-29 16:59:29+05:30

In [24]:
k = input("give the file name : ")

filterdata.to_csv(f"{str(k)}.csv")

give the file name : m2